spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false

  jpa:
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: starter

server:
  address: 0.0.0.0
  port: 8080

datasource:
  login:
    user: ${DATA_ADMIN_USER}
    password: ${DATA_ADMIN_PASSWORD}
  telemetry:
    url: ${TELEMETRY_STORE_URL}
    org: ${TELEMETRY_STORE_ORG}
    bucket: ${TELEMETRY_STORE_BUCKET}
    token: ${TELEMETRY_STORE_TOKEN}
  data:
    url: ${DATA_STORE_URL}
    org: ${DATA_STORE_ORG}
    bucket: ${DATA_STORE_BUCKET}
    token: ${DATA_STORE_TOKEN}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY}
    registerWithEureka: true
    fetchRegistry: true

management:
  port: 8081
  endpoints:
    web:
      exposure:
        include: '*'