/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_RevPiReader */

#ifndef _Included_org_example_RevPiReader
#define _Included_org_example_RevPiReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_RevPiReader
 * Method:    readFromOffset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_RevPiReader_readFromOffset
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
