version: "3.5"

volumes:
  metastore-data:
  datastore-data:

networks:
  components:
    name: pegelhub-components

  meta-net:
    name: pegelhub-metastore

  data-net:
    name: pegelhub-datastore

services:
  registry:
    build:
      context: service-registry
    restart: on-failure
    networks:
      - components

  # backend components
  meta-db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=$META_PASSWORD
      - POSTGRES_DB=$META_DB
    volumes:
      - "metastore-data:/var/lib/postgresql"
    ports:
      - "5444:5432"
    networks:
      - meta-net


  data-db:
    image: influxdb:latest
    restart: on-failure
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$DATA_ADMIN_USER
      - DOCKER_INFLUXDB_INIT_PASSWORD=$DATA_ADMIN_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$DATA_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$INTERNAL_DB
      - BUCKET_TELEMETRY=$TELEMETRY_DB
      - BUCKET_DATA=$DATA_DB
      - STORE_USER=$DATA_USER
    volumes:
      - "datastore-data:/var/lib/influxdb"
      - "./init-influxdb.sh:/docker-entrypoint-initdb.d/00-setup.sh"
      - "./.datastoreconfig:/etc/influxdb2/store/"
    ports:
      - "8111:8086"
    networks:
      - data-net

  # edge components
  starter:
    build:
      context: starter
    restart: on-failure
    environment:
      - DB_URI=meta-db:5432/$META_DB
      - DB_USER=postgres
      - DB_PASSWORD=$META_PASSWORD
      - TELEMETRY_STORE_URL=http://data-db:8086/
      - TELEMETRY_STORE_ORG=$DATA_USER
      - TELEMETRY_STORE_BUCKET=$DATA_DB
      - TELEMETRY_STORE_TOKEN=$DATA_PASSWORD
      - DATA_ADMIN_USER=$DATA_ADMIN_USER
      - DATA_ADMIN_PASSWORD=$DATA_ADMIN_PASSWORD
      - DATA_STORE_URL=http://data-db:8086/
      - DATA_STORE_ORG=$DATA_USER
      - DATA_STORE_BUCKET=$DATA_DB
      - DATA_STORE_TOKEN=$DATA_PASSWORD
      - INFLUX_FILE=/etc/influxdb2/store/storeapp.yaml
    volumes:
      - "./.datastoreconfig:/etc/influxdb2/store/"
    depends_on:
      - registry
      - meta-db
      - data-db
    networks:
      - components
      - meta-net
      - data-net

  # exposed proxy service
  proxy:
    build:
      context: routing-proxy
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - registry
      - starter
    networks:
      - components
