spring:
  application:
    name: routing-proxy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    # ------------------
    # routing properties
    # ------------------
    gateway:
      discovery:
        locator:
          enabled: true
      filter:
        secure-headers:
          disable: Authorization
      routes:
        - uri: lb://STARTER/
          predicates:
            - Path=/services/management/**
          filters:
            - RewritePath=/services/management/(?<segment>.*),/api/v1/$\{segment}
        - uri: lb://STARTER/
          predicates:
            - Path=/services/store/**
          filters:
            - RewritePath=/services/store/(?<segment>.*),/api/v1/$\{segment}
        - uri: lb://STARTER/
          predicates:
            - Path=/**

server:
  address: 0.0.0.0
  port: ${APP_PORT}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY}
    registerWithEureka: true
    fetchRegistry: true

management:
  port: 8181
  endpoints:
    web:
      exposure:
        include: '*'