spring:
  application:
    name: component-registry
server:
  address: 0.0.0.0
  port: ${APP_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  port: 8081
  endpoints:
    web:
      exposure:
        include: '*'